---
#
- debug:
    msg: "apache tomee {{ apache_tomee_edition }} {{ apache_tomee_version }} will be downloaded from {{ apache_tomee_url }} to {{ apache_tomee_home }}"

- name: install apache tomee
  unarchive:
    src: "{{ apache_tomee_url }}"
    dest: "{{ apache_tomee_base }}"
    owner: "{{ apache_tomee_user }}"
    group: "{{ apache_tomee_group}}"
    copy: no
    creates: "{{ apache_tomee_home }}/bin/catalina.sh"
  become: yes
