---
# tasks file for apache-tomee
- include: prepare.yml
  become: yes
  tags:
    - preinstall

- include: validate.yml
  become: yes
  become_user: "{{ tomee_user }}"

- include: install.yml
  when: not apache_tomee_already_installed
  tags:
    - install

- include: configure.yml
  tags:
    - configure
