---
#
- group:
    name: "{{ apache_tomee_group }}"
    state: present

- user:
    name: "{{ apache_tomee_user }}"
    group: "{{ apache_tomee_group }}"
    home: "/opt/{{ apache_tomee_user }}"
    createhome: yes
    state: present

- name: install unarchive packages
  package: name={{ item }} state=latest
  with_items:
    - unzip
    - tar
